### ISSUE TITLE
Two phantom structure visuals shown in building mode

### ISSUE THREAD

**Issue by perfecthumaninterface** [alkaitagi/ProjectBurst#56]
When in build mode with grid snapping engaged, there are two phantom structure visuals attached to the mouse position where there should be only one. 

(I tried to take a screenshot of this but for some reason it doesn't capture both of them when I press printscrn even though I had to had to use my face to press the key.)

It also seems the building will place if either one of them is in a valid place even if one or the other is red.

**Comment by alkaitagi** [comment]
> even though I had to had to use my face to press the key
Appreciate the effort.

**Comment by alkaitagi** [comment]
I was only able to briefly reproduce the bug for a few frames, but not on consistent basis. They are not different structures, its the same object but rapidly jumping between the mouse position and its snap. I suspect that it happens because I first move preview to mouse position, and then, if `IsSnapped` flag is true, snap it. In other words, multiple single transform moves within a single frame. Hopefully fixed by batching position computations and moving transform only once.

**Comment by perfecthumaninterface** [comment]
I don't see it happening anymore so I'll assume it's fixed.
